### ISSUE TITLE
File download error 

### ISSUE THREAD

**Issue by DogancanYr** [agam778/MS-Office-Electron#38]
I'm downloading a file (.pptx) and white screen

**Comment by agam778** [comment]
Is it an enterprise account or a personal account?

**Comment by DogancanYr** [comment]
Personal account .

**Comment by agam778** [comment]
Can you show a video illustration if possible?

Also, are you using "Open Websites in New Windows" or "Open Websites in Same Window"?

**Comment by DogancanYr** [comment]
Open Websites in Same Window .

**Comment by agam778** [comment]
> Can you show a video illustration if possible?

**Comment by DogancanYr** [comment]
https://user-images.githubusercontent.com/90002969/170876407-5e697ad0-6322-4961-a4ff-fa573aa3df9f.mp4

**Comment by agam778** [comment]
Probably the issue is something with "Open websites in Same WIndow" because it forces the download url to be opened in the same window which doesn't download the file I guess, but works for me when I use the "Open Websites in New WIndow" option because the download url in the MS Office website is set to be opened in a new tab probably.

**Comment by DogancanYr** [comment]
Only in word .

**Comment by DogancanYr** [comment]
I guess I'll find another app.
