### ISSUE TITLE
Select URL auth office

### ISSUE THREAD

**Issue by gunter423** [agam778/MS-Office-Electron#72]
Hi,

Can I integrate this feature :

When user open app it can select url auth `https://office.com/?auth=1` or `https://office.com/?auth=2`

Or maybe that feature is currently being development ?

Have a nice day :)

**Comment by agam778** [comment]
![image](https://user-images.githubusercontent.com/68941022/191174334-b50fb78a-d84e-4c27-97fa-67986dedc75e.png)

That feature is already there in the app, 

Click on Application in the menu bar and select `Open Normal version of MS Office` for opening the app with `https://office.com/?auth=1`

and `Open Enterprise version of MS Office` for opening the app with `https://office.com/?auth=2`

You can close the issue if the problem is solved, Thanks for using my app!

**Comment by gunter423** [comment]
oh yes I hadn't seen, thanks :+1:
